### PR TITLE
Add option to change default implicit uri scheme

### LINKED ISSUE #23: Is there some sort of a solution to disparity in image paths between WASM and native targets?

### PR DESCRIPTION
**Pull request by lampsitter**
Fixes #23 

Would this work for you @JohnDowson?

### CODE REVIEW

**Comment by JohnDowson** [comment]
Weird issue. When doing something like this,

```rust
let cmv = CommonMarkViewer::new("TUTORIAL.md");
        #[cfg(target_arch = "wasm32")]
                let cmv = cmv.default_implicit_uri_scheme("http://127.0.0.1:8080/rack-designer/");
                        cmv.show(ui, &mut cache, TUTORIAL);
```

on native I get an image, while on WASM I now get a red warning icon with hover-text of "Failed to load such and such. The image format Png is not supported."
I do have the `fetch` feature enabled.

**Comment by JohnDowson** [comment]
Other than that, it's exactly what I've wanted.

**Comment by JohnDowson** [comment]
> Weird issue. ....

Actually, this liiks like it might have more to do with @emilk 's [egui_extras](https://github.com/emilk/egui/tree/master/crates/egui_extras), given you don't seem to have any cfg gates to disable some image loaders.

**Comment by JohnDowson** [comment]
So, the work-around is to add `image = { version = "0.24", features = ["png"] }` to my dependencies on `wasm32` targets.

**Comment by emilk** [comment]
`eframe` uses the `png` feature to load the native application icon (if any).

By design, `egui_extras` does not enable all the image formats in the `image` crate, because there is a lot of them and it adds dependencies, compilation time, and binary bloat. That's why users needs to opt-in to the image formats they want.

**Comment by JohnDowson** [comment]
> `eframe` uses the `png` feature to load the native application icon (if any).
> 
> By design, `egui_extras` does not enable all the image formats in the `image` crate, because there is a lot of them and it adds dependencies, compilation time, and binary bloat. That's why users needs to opt-in to the image formats they want.

What tripped me up is that it works on native without explicitly enabling the `png` feature of the `image` crate.

**Pull request merged**
